version: '3'

services:
  flask:
    build: ./flask
    ports:
      # Use 5000:80 when attempting to deploy with uwsgi+nginx
      # - 5000:80
      - 5000:5000
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  
  db:
    image: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
