version: '3'

services:
  flask:
    build: ./flask
    ports:
      - 5000:80
    depends_on:
      - db
  
  db:
    image: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data