version: '3'

services:

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - flask

  flask:
    build: ./flask
    # ports:
      # - 5000:5000
      # - 8080:8080
    expose:
      - 8080
    depends_on:
      - db
  
  worker:
    build: ./worker
    depends_on:
      - flask
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
  
  db:
    image: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
